CREATE TABLE public.processed_events (
	id serial4 NOT NULL,
	topic varchar NOT NULL,
	kafka_partition int4 NOT NULL,
	kafka_offset int8 NOT NULL,
	"key" varchar NULL,
	id_event uuid NOT NULL,
	payload varchar(255) NOT NULL,
	consumer_group varchar NOT NULL,
	processed_at timestamp NOT NULL,
	processing_time_ms int4 NULL,
	status varchar NOT NULL,
	client_id varchar(50) NOT NULL,
	"type" varchar(30) NOT NULL,
	"source" varchar(30) NOT NULL,
	severity varchar(30) NOT NULL,
	sent_at timestamp NOT NULL,
	"version" varchar(10) NULL,
	CONSTRAINT processed_events_pk PRIMARY KEY (id),
	CONSTRAINT processed_events_uk UNIQUE (topic, kafka_partition, kafka_offset)
);